version: "2"
services:
  tc-notifications-base:
    build:
      context: ./generic-tc-service
      args:
        NODE_VERSION: 8.11.3
        GIT_URL: https://github.com/topcoder-platform/tc-notifications
        GIT_BRANCH: dev
        BYPASS_TOKEN_VALIDATION: 1
    environment:
      - VALID_ISSUERS="[\"https://topcoder-newauth.auth0.com/\",\"https://api.topcoder-dev.com\"]"
      - TC_API_V5_BASE_URL=http://host.docker.internal:8001/v5
      - TC_API_V4_BASE_URL=https://api.topcoder-dev.com/v4
      - TC_API_V3_BASE_URL=https://api.topcoder-dev.com/v3
      - KAFKA_URL=kafka:9093
      - AUTH_SECRET=secret
      - DATABASE_URL=postgresql://coder:mysecretpassword@db:5432/tc_notifications
      - JWKS_URI=test
      - LOG_LEVEL=debug
      - ENV=development
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_URL
      - AUTH0_AUDIENCE
      - AUTH0_PROXY_SERVER_URL
